### ISSUE TITLE
no more Pushbullet app for iOS

### ISSUE THREAD

**Issue by mdhoney** [camerahacks/rpilocator-rss-feed#1]
Thank you for coming up with this script!  I was about to give it a try, when I realized the iOS Pushbullet app is no more. 😐 ([Apparently they removed it from the App Store two years ago.](https://www.reddit.com/r/PushBullet/comments/eirc1m/not_available_on_ios/fcxybyu/))
Are there any alternative notification systems you can suggest?

**Comment by hugepants** [comment]
Pushover is a good alternative.

**Comment by camerahacks** [comment]
I'll work on a pushover version. I'm also considering creating Pushover groups to broadcast notifications.

**Comment by mdhoney** [comment]
Thanks @camerahacks for publishing a Pushover version so promptly!  Running it as we speak.  Now I just need to wait for some stock to show up... 😛

**Comment by camerahacks** [comment]
No problem.
