### ISSUE TITLE
Doesn't run by itself every 1 minutes

### ISSUE THREAD

**Issue by Rubiooo04** [camerahacks/rpilocator-rss-feed#11]
I run the script with this command `nohup python3 rpilocator-rss-ntfy.py & ` but it only runs 1 time and then it stays without doing anything  in the nohup.out nothing comes out

**Comment by Rubiooo04** [comment]
https://user-images.githubusercontent.com/77902247/206907241-6c532a24-5462-4bcb-a523-80b924803ca3.mp4

**Comment by camerahacks** [comment]
You didn't give a whole lot of info but it looks like you are expecting a notification to be sent right away. A notification is only sent when there is a new product in stock. I'm not entirely sure what you mean by "it only runs once". The script has an infinite loop within it.

nohup will only write to the file if there is output.

Did you make changes to the scripts?
