### ISSUE TITLE
Twilio integration

### ISSUE THREAD

**Issue by ragenhe** [camerahacks/rpilocator-rss-feed#13]
Any chance we can get a "Twilio" version of the py?

Or a node-red "http request".

I am trying, with node-red, and have made some progress..... but can't figure it all out.

**Comment by camerahacks** [comment]
Twilio is an enterprise product and I will not prioritize it. Also, keep in mind that using the feed or rpilocator's info for business or commercial purposes is against our fair use policy.

https://rpilocator.com/about.cfm

**Comment by ragenhe** [comment]
No business use, for twilio or buying the pis. I use twilio as an SMS gateway for my home assistant alerts. I’m sure twilio can be used for much more, but my use of it is far less then enterprise.

Thank you!
Ragen
________________________________

**Comment by camerahacks** [comment]
I wasn't saying you are using it for business purposes, I was just adding that as a reminder. Lots of people will search for the terms Twilio + rpilocator and get to this issue.

If you get it to work, feel free to do a pull request.

**Comment by ragenhe** [comment]
Thank you for the clarification.

Will do on the pull request!

Thank you!
Ragen
________________________________

**Comment by camerahacks** [comment]
@ragenhe , did you get it to work?

**Comment by ragenhe** [comment]
I deployed the node-red flow. Works like a champ.

Thanks!!

Thank you!
Ragen
________________________________
