### ISSUE TITLE
Check New Alerts Node Error

### ISSUE THREAD

**Issue by FinestDice17** [camerahacks/rpilocator-rss-feed#15]
"TypeError: entries is not iterable

![Capture](https://user-images.githubusercontent.com/68380500/213697349-0cdd9c26-ca2c-4227-bfb2-a164f2715310.PNG)

**Comment by camerahacks** [comment]
Can you add more information? The URL you are hitting, what you have looked into, and possible solutions would all be useful information to add when you open an issue. Thanks

**Comment by FinestDice17** [comment]
> Can you add more information? The URL you are hitting, what you have looked into, and possible solutions would all be useful information to add when you open an issue. Thanks

URL used ----->>>  https://rpilocator.com/feed/?country=US,CA&cat=CM4

and i copied your node red json script into a new flow in node red and just added my pushover node at the end instead of the pushbullet one that you had at the end of the flow. 

Ive also tried the pushover.py script and i get an exit 2 code using the same URL.

**Comment by camerahacks** [comment]
Ok, yeah, there hasn't been any CM4s in the US and Canada for a while so the object "entries" doesn't have anything. It just needs some error checking in case entries doesn't exist.

**Comment by FinestDice17** [comment]
> Ok, yeah, there hasn't been any CM4s in the US and Canada for a while so the object "entries" doesn't have anything. It just needs some error checking in case entries doesn't exist.

oh ok! I appreciate your help with this.

**Comment by camerahacks** [comment]
This is fixed. Thanks!
