### ISSUE TITLE
Super Silly Question - basic node red question

### ISSUE THREAD

**Issue by Austin1** [camerahacks/rpilocator-rss-feed#17]
I was able to install node-red, import this flow, but I have no idea if it's working. Is there a way to easily test the workflow, making it think there is a new item to notify me on?

**Comment by camerahacks** [comment]
You can try deleting an item from the array that holds of the notifications currently on the feed with array.splice(index, 1);

So, if you haven't made any changes to the "Check new alerts" node, you can add the code below to line 21. Make sure to delete it after you test it.

`control.splice(0,1);`

You should get an alert for the very first item in the feed.

**Comment by Austin1** [comment]
Hmm, still haven't been able to get a push notification using pushbullet. I added my api key and tried adding control.splice(0,1); I then clicked the inject button next to timestamp to kick it off and nothign happens. I can't see what is going on, like it doesn't seem to tell me anything useful anywhere that I can see, but it's obviously me being a newbie with it. 

```
var control = context.get('control');

var rss = msg.payload.rss;

var entries = rss.channel[0].item;

var MESSAGE_TITLE = 'xlocator Stock Alert'

var result = {};

if(control===undefined){
    control = []
    
        if(entries !== undefined){
            for (const entry of entries) {
                control.push(entry.guid[0]._);
            }
        }

}
control.splice(0,1);
if (entries !== undefined) {
    for (const entry of entries) {
        if (!control.includes(entry.guid[0]._)){
            var guidEntry = (entry.guid[0]._);

            node.warn(entry);

            var message = { 'type': 'link', 'title': MESSAGE_TITLE, 'body': entry.title[0], 'url': entry.link[0] }

            node.warn(message);
            
            control.push(entry.guid[0]._);

            msg.payload = message;

            node.send(msg)
        }
    }
}

context.set('control', control)

return;
```

Is there any messages anywhere that tell me what is happening? I tried adding a debug node to end but that was pointless.
<img width="1039" alt="Screenshot 2024-01-03 at 7 26 18 PM" src="https://github.com/camerahacks/rpilocator-rss-feed/assets/341408/c5024091-7589-42f7-ac6c-6e85605b63c0">

**Comment by camerahacks** [comment]
The blue dots mean you didn't deploy the flow so the debug nodes weren't working yet and it doesn't look like the changes you made to the Pushbullet node were saved either.

I just tried the suggestion I gave and I received a pushbullet notification right away.

**Comment by Austin1** [comment]
ok yea, I had deployed it, but I was using a custom URL that just didn't have any data in it. So I used your example from the README and I got a push! So thanks for the help!
