### ISSUE TITLE
Webhook RSS Feed Aggregator

### ISSUE THREAD

**Issue by StappsWorld** [camerahacks/rpilocator-rss-feed#3]
@GabrielHogan and I actually made a similar project a week ago that will automatically inform users via a webhook. In our case, we wanted a Discord message, so we used Discord webhooks.

Perhaps this functionality could be implemented into the official script?

https://github.com/Reman-Hogbisz/pi_watcher

**Comment by camerahacks** [comment]
Feel free to create a pull request. Please follow the structure from one of the existing scripts.
