### ISSUE TITLE
Nice to have: a log or output from the script

### ISSUE THREAD

**Issue by rajdude** [camerahacks/rpilocator-rss-feed#6]
(Not really an bug or an issue, just a request)
ok I got the script running on Windoze + Python + Pushover to my Android phone. Notification test from pushover's website works fine. When I run the script, there is no script output. I wonder if there is a way to test that script. I do not want to miss a notification :-)

I noticed that on Pushover's website, my registered application now appears in the drop down for sending a test notification. I tried it, it did send out a notification. Still there was no output from the script at the console. I am no programmer, but won't it be nice to have some kind of output on the console, or maybe a log from the Python script?

**Comment by rajdude** [comment]
I have one more observation....just as a test, I killed the script running on my machine. Then used Pushover to send a notification through my rpilocator application there. My phone still got a notification. I guess that means the script is not really working?

Sorry, not sure if the notifications are routed through the script, or the script sends out a notification to Pushover, and thereafter Pushover sends the notification.

**Comment by camerahacks** [comment]
The script will send a request to Pushover's server so they can send a message to your phone. The message is only sent if there is a new stock notification since that's what's in the RSS feed. I don't see a need for output since this is a script meant to run in the background.

If you want to test the script, you can modify it with the code block below so it removes the last "control" item. This should cause the  script to "think" there is a new stock notification.

```
# Locate this piece of the code
time.sleep(30)

# Add this below the piece of code above
control.pop()
```

Make sure to remove ```control.pop()``` once you have tested.

**Comment by rajdude** [comment]
Thank you very much for the input. I really appreciate it.. I'll test your suggestion and report back soon.

**Comment by rajdude** [comment]
I tried your suggestion, I did not get a notification, but got this error on the console:

_Traceback (most recent call last):
  File "D:\Data\Software\scripts\rpilocator-rss-pushover.py", line 60, in <module>
    control.pop()
IndexError: pop from empty list_

script looks like this:

---------snip------------

#Only wait 30 seconds after initial run.
time.sleep(30)

control.pop()

while True:
    # Fetch the feed again, and again, and again...
    f = feedparser.parse(FEED_URL, agent=USER_AGENT)

--------snip-----------

Tried it twice, same message.
Boy! I wish I knew coding :-( Gotta learn Python

**Comment by camerahacks** [comment]
Yeah, it will be hard to troubleshoot this way. If the control list/variable is empty, it probably means your computer/python was not able to download the feed. Firewall??

**Comment by rajdude** [comment]
thanks for checking and replying. I am now trying to learn Python.

If I run a simple script to get your page, it does work fine. 
For example running this script...

```
import requests

x = requests.get('https://rpilocator.com/?country=US')
print(x.status_code)
print(x.text)
```

...gives me this

````
200

<!doctype html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Find Raspberry Pi computers in stock with this simple to use web application.">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

----snipped---------
````


That probably means that firewall is not an issue. Python is able to get that page from the internet.

I do remember I modified these two lines in your script yesterday, maybe they are making some difference which I misunderstand. Let me revert it back to your original and test.

````
# Customize the message title
MESSAGE_TITLE = 'xlocator Stock Alert'

# User Agent
USER_AGENT = 'xlocator feed alert'
````

BRB

**Comment by rajdude** [comment]
Nope, still the same error message. 

````
C:\Users\Rajeev>py D:\Data\Software\scripts\rpilocator-rss-pushover.py
Traceback (most recent call last):
  File "D:\Data\Software\scripts\rpilocator-rss-pushover.py", line 60, in <module>
    control.pop()
IndexError: pop from empty list
````

**Comment by rajdude** [comment]
Did some more troubleshooting. It seems to me feedparser is not liking the output of the RSS feed at rpilocator.

As a test I compared two RSS feeds, like this

````
#f = feedparser.parse('https://rpilocator.com/feed/?country=US')
f = feedparser.parse('http://www.reddit.com/r/python/.rss')
print (f.entries[0].keys())
````
outputs:

````

dict_keys(['authors', 'author_detail', 'href', 'author', 'tags', 'content', 'summary', 'id', 'guidislink', 'link', 'links', 'updated', 'updated_parsed', 'published', 'published_parsed', 'title', 'title_detail'])
````
Which shows all the keys associated with the entries. Good!

But this
````
f = feedparser.parse('https://rpilocator.com/feed/?country=US')
#f = feedparser.parse('http://www.reddit.com/r/python/.rss')
print (f.entries[0].keys())
````
outputs:

````

Traceback (most recent call last):
  File "D:\Data\Software\scripts\rpilocator-rss-pushoverTEST.py", line 18, in <module>
    print (f.entries[0].keys())
IndexError: list index out of range

````


Hmmmm :-(

**Comment by camerahacks** [comment]
The feed only stores the last 20-25 alerts (can't remember the exact number). You are filtering the feed to US items only and there aren't any US items on the feed right now since there has been 20-25 alerts since the last US alert.

For instance, if you change the filter to NL instead of US and leave the line for control.pop() you should be able to test it.

If you find any problems, please open a new issue.
